# Workflow name
name: Post random Messi image to Twitter

# Workflow trigger
on:
  schedule:
    - cron: "0 20 * * *" # 17:00 ARG
    - cron: "0 24 * * *" # 21:00 ARG
  workflow_dispatch: # Manual GitHub Actions

# Jobs to do
jobs:
  post-tweet:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Clonar el repositorio
        uses: actions/checkout@v3

      - name: ğŸŸ¢ Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: ğŸ“¦ Instalar dependencias
        run: npm ci

      - name: ğŸ”§ Compilar TypeScript
        run: npx tsc

      - name: ğŸ”‘ Configurar variables de entorno
        run: |
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> .env
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> .env
          echo "CLOUD_NAME=${{ secrets.CLOUD_NAME }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env

      - name: ğŸš€ Ejecutar bot
        run: node dist/main.js
